{% set name = "yosys" %}
{% set version = "0.34" %}
{% set sha256 = "57897bc3fe5fdc940e9f3f3ae03b84f5f8e9149b6f26d3699f7ecb9f31a41ae0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/YosysHQ/{{ name }}/archive/refs/tags/yosys-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison
    - make
    - pkg-config
  host:
    - libboost-python-devel
    - flex
    - libffi
    - libzlib
    - readline
    - tk
    - zlib
  run:
    - graphviz
    - libffi
    - libzlib
    - readline
    - tk

test:
  commands:
    - yosys-config --prefix
    - yosys-config --ldflags

about:
  home: https://github.com/YosysHQ/yosys
  license: ISC
  license_family: OTHER
  license_file: COPYING
  summary: Yosys Open SYnthesis Suite
  description: |
    This is a framework for RTL synthesis tools. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.
  dev_url: https://github.com/YosysHQ/yosys

extra:
  recipe-maintainers:
    - whitequark
    - timkpaine
